global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'snmp'
    scrape_timeout: 50s
    static_configs:
      - targets:
        - 172.30.48.254 # SNMP device.
      # - tcp://10.255.0.74:161
    metrics_path: /snmp
    params:
      auth: [public_v1]
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.30.48.28:9116

  # Global exporter-level metrics
  - job_name: 'snmp_exporter'
    static_configs:
      - targets: ['172.30.48.28:9116']


