version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www/html
      - ./nginx/snippets:/etc/nginx/snippets
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/nginx-selfsinged.crt:/etc/nginx/ssl/nginx-selfsigned.crt
      - ./src/nginx-selfsinged.key:/etc/nginx/ssl/nginx-selfsinged.key

    depends_on:
      - php
      - postgres


  php:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
  #    POSTGRES_DB: aangiftes
    ports:
      - "5432:5432"
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d 
