# Dockerfile

FROM php:7.4-fpm

# Install required dependencies
RUN apt-get update && apt-get install -y libpq-dev

# Install PostgreSQL driver for PHP
RUN docker-php-ext-install pdo_pgsql

# Cleanup
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

CMD ["php-fpm"]
